server:
  port: 8080

jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86G

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: backend-user
            uri: lb://backend-user
            predicates:
              - Path=/api/user/**
            filters:
              - AddAuthenticationHeader
          - id: backend-alim
            uri: lb://backend-alim
            predicates:
              - Path=/api/alim/**
            filters:
              - AddAuthenticationHeader
